import type { Round } from './types';

const provenance = '2026.08.22 수험생 비공식 실전 제보 키워드와 저장소 유사 기출을 바탕으로 재구성';

export const hvacFieldReportRound: Round = {
  id: 'hvac-field-report-2026-08-22',
  qualificationKey: 'hvac',
  qualification: '공조냉동기계산업기사',
  shortQualification: '공조냉동',
  year: 2026,
  session: '8월 22일 실전 제보',
  date: '2026.08.22',
  sortKey: '20260822-field-report',
  title: '2026년 8월 22일 비공식 실전 복원 훈련',
  kind: 'field-report-practice',
  subjects: ['공기조화설비', '냉동냉장설비', '공조냉동설치운영'],
  questions: [
    {
      number: 1,
      _subject: '공기조화설비',
      text: '방열기의 호칭 표시에서 가운데 단에 적는 내용은?',
      choices: [
        { text: '유입관의 크기' },
        { text: '유출관의 크기' },
        { text: '절(section) 수' },
        { text: '방열기의 종류와 높이' },
      ],
      answer: 4,
      explanation: '방열기 호칭은 위치별로 읽습니다. 가운데 단은 방열기의 종류와 높이, 위쪽은 절수, 아래쪽은 유입·유출 관경을 나타냅니다. 쉽게 외우기: “가운데에는 몸통 정보인 종류·높이”라고 기억하세요. 유사 기출: 2002년 5월 12번, 2011년 6월 18번, 2023년 3회 8번.',
      source: provenance,
      explanationProvenance: provenance,
    },
    {
      number: 2,
      _subject: '공기조화설비',
      text: '같은 송풍기에서 회전수만 2배가 되었다. 풍량·압력·동력은 각각 몇 배가 되는가?',
      choices: [
        { text: '풍량 2배, 압력 2배, 동력 2배' },
        { text: '풍량 2배, 압력 4배, 동력 8배' },
        { text: '풍량 4배, 압력 4배, 동력 8배' },
        { text: '풍량 8배, 압력 4배, 동력 2배' },
      ],
      answer: 2,
      explanation: '회전수에 대한 송풍기 상사법칙은 풍량 1제곱, 압력 2제곱, 동력 3제곱입니다. 회전수비가 2이면 풍량은 2, 압력은 2²=4, 동력은 2³=8배입니다. 쉽게 외우기: “풍압동 1·2·3”. 유사 기출: 2015년 3월 2번, 2016년 3월 8번, 2021년 2회 10번, 2024년 3회 8번.',
      source: provenance,
      explanationProvenance: provenance,
    },
    {
      number: 3,
      _subject: '공기조화설비',
      text: '서로 닮은 송풍기의 회전수가 같고 날개 지름만 바뀔 때, 풍량·압력·동력의 지름에 대한 비례 관계로 옳은 것은?',
      choices: [
        { text: '풍량 D, 압력 D², 동력 D³' },
        { text: '풍량 D², 압력 D³, 동력 D⁴' },
        { text: '풍량 D³, 압력 D², 동력 D⁵' },
        { text: '풍량 D³, 압력 D⁴, 동력 D⁵' },
      ],
      answer: 3,
      explanation: '회전수비만 볼 때는 1·2·3이지만 지름비는 풍량 D³, 압력 D², 동력 D⁵입니다. 제보 댓글의 “1·2·3”과 “3·2·5”는 조건이 달라 둘 다 나올 수 있습니다. 쉽게 외우기: 회전수는 123, 지름은 325. 유사 기출: 2016년 3월 8번, 2022년 1회 3번.',
      source: provenance,
      explanationProvenance: provenance,
    },
    {
      number: 4,
      _subject: '냉동냉장설비',
      text: '냉매 R-21의 화학식은?',
      choices: [
        { text: 'CHCl₂F' },
        { text: 'CHClF₂' },
        { text: 'CCl₂F₂' },
        { text: 'NH₃' },
      ],
      answer: 1,
      explanation: 'R-21은 CHCl₂F입니다. 보기의 CHClF₂는 R-22, CCl₂F₂는 R-12, NH₃는 R-717입니다. 숫자와 화학식은 한 번에 전부 외우기보다 R-21·R-22·R-12·R-717 네 개를 묶어 비교하세요. 유사 기출: 2011년 3월 28번, 2019년 8월 26번.',
      source: provenance,
      explanationProvenance: provenance,
    },
    {
      number: 5,
      _subject: '냉동냉장설비',
      text: '2원 냉동장치의 저온측 냉매로 가장 적합하지 않은 것은?',
      choices: [
        { text: 'R-22' },
        { text: 'R-14' },
        { text: '에틸렌' },
        { text: '메탄' },
      ],
      answer: 1,
      explanation: '아주 낮은 온도를 만드는 저온측에는 R-14, 에틸렌, 메탄처럼 저온용 냉매를 사용합니다. R-22는 이 보기들 가운데 저온측용으로 적합하지 않습니다. 쉽게 외우기: “극저온은 R-14와 아주 가벼운 탄화수소”. 유사 기출: 2014년 3월 28번.',
      source: provenance,
      explanationProvenance: provenance,
    },
    {
      number: 6,
      _subject: '냉동냉장설비',
      text: '냉매와 냉동기유의 관계에 대한 설명으로 옳은 것은?',
      choices: [
        { text: '암모니아는 냉동기유에 매우 잘 녹는다.' },
        { text: 'R-12는 냉동기유에 비교적 잘 녹는다.' },
        { text: 'R-22는 온도와 관계없이 냉동기유에 전혀 녹지 않는다.' },
        { text: '모든 냉매는 냉동기유와 잘 섞여야만 한다.' },
      ],
      answer: 2,
      explanation: '냉매마다 냉동기유와 섞이는 성질이 다릅니다. 암모니아는 잘 녹지 않고, R-12는 잘 녹으며, R-22는 높은 온도에서는 잘 녹지만 낮은 온도에서는 덜 녹습니다. 그래서 “모든 냉매는 무조건 잘 섞여야 한다”는 말은 틀립니다. 유사 기출: 2012년 3월 34번.',
      source: provenance,
      explanationProvenance: provenance,
    },
    {
      number: 7,
      _subject: '냉동냉장설비',
      text: '빙축열 장치의 코일 안을 순환하며 물을 얼릴 때 냉열을 운반하는 2차 냉매는?',
      choices: [
        { text: '브라인' },
        { text: '윤활유' },
        { text: '응축수' },
        { text: '증기' },
      ],
      answer: 1,
      explanation: '제보에는 펌프의 정확한 문제 문장과 보기가 남아 있지 않아 확인 가능한 핵심 원리로 재구성했습니다. 빙축열에서는 저온의 브라인이 코일 안을 돌며 냉열을 운반하고 코일 바깥의 물을 얼립니다. 브라인은 상태가 바뀌는 잠열이 아니라 온도차에 의한 감열을 이용하는 2차 냉매입니다. 유사 기출: 2005년 3월 33번, 2009년 5월 15번.',
      source: provenance,
      explanationProvenance: provenance,
    },
    {
      number: 8,
      _subject: '공조냉동설치운영',
      text: '일반 공기조화용 덕트 재료로 가장 널리 사용하는 것은?',
      choices: [
        { text: '동판' },
        { text: '알루미늄 판' },
        { text: '일반 탄소강판' },
        { text: '아연도금 강판' },
      ],
      answer: 4,
      explanation: '일반 덕트는 녹에 비교적 강하고 가공하기 쉬운 아연도금 강판을 가장 많이 사용합니다. 특수한 조건에서는 스테인리스·알루미늄 등을 쓰지만 “일반적으로 가장 많이”라는 조건이면 아연도금 강판입니다. 유사 기출: 2011년 8월 17번.',
      source: provenance,
      explanationProvenance: provenance,
    },
    {
      number: 9,
      _subject: '공조냉동설치운영',
      text: '펌프의 캐비테이션을 막는 방법으로 틀린 것은?',
      choices: [
        { text: '펌프 회전수를 더 빠르게 한다.' },
        { text: '흡입배관의 굽힘을 줄인다.' },
        { text: '흡입관경을 크게 한다.' },
        { text: '흡입양정을 짧게 한다.' },
      ],
      answer: 1,
      explanation: '캐비테이션은 펌프 입구 압력이 너무 낮아져 기포가 생겼다가 터지는 현상입니다. 회전수를 높이면 입구 압력이 더 떨어질 수 있으므로 방지책이 아닙니다. 흡입관은 굵고 짧고 곧게, 회전수는 낮게가 기본입니다. 유사 기출: 2012년 3월 46번, 2015년 3월 60번, 2019년 8월 46번.',
      source: provenance,
      explanationProvenance: provenance,
    },
    {
      number: 10,
      _subject: '공기조화설비',
      text: '병원 수술실이나 식품공장에서 먼지뿐 아니라 세균·곰팡이·바이러스까지 관리하는 설비는?',
      choices: [
        { text: '바이오 클린룸' },
        { text: '제습실' },
        { text: '항온항습실' },
        { text: 'VAV 시스템' },
      ],
      answer: 1,
      explanation: '바이오 클린룸(BCR)은 미세먼지뿐 아니라 살아 있는 미생물 오염까지 관리합니다. 병원·제약·식품이라는 말이 보이면 바이오를 먼저 떠올리세요. 유사 기출: 2002년 3월 9번, 2019년 3월 17번, 2022년 2회 8번.',
      source: provenance,
      explanationProvenance: provenance,
    },
    {
      number: 11,
      _subject: '공기조화설비',
      text: '공기필터의 용도와 종류를 바르게 연결한 것은?',
      choices: [
        { text: '냄새·유해가스 제거 — 활성탄 필터' },
        { text: '미세입자 고효율 제거 — 롤 필터' },
        { text: 'HEPA 성능 측정 — 중량법' },
        { text: '큰 먼지 1차 제거 — HEPA 필터' },
      ],
      answer: 1,
      explanation: '활성탄은 표면에 냄새와 유해가스를 흡착합니다. HEPA는 미세입자를 높은 효율로 제거하고 성능은 DOP법·계수법 계열로 확인합니다. 보통 프리필터 → 중성능 필터 → HEPA 순서입니다. 유사 기출: 2013년 3월 5번, 2013년 8월 7번, 2022년 1회 8번, 2026년 2회 13번.',
      source: provenance,
      explanationProvenance: provenance,
    },
    {
      number: 12,
      _subject: '냉동냉장설비',
      text: '냉동장치에서 팽창밸브가 너무 적게 열렸을 때 나타나는 현상은?',
      choices: [
        { text: '증발기에 냉매가 부족해지고 증발압력이 낮아진다.' },
        { text: '액 냉매가 과다 공급되어 리퀴드백이 반드시 생긴다.' },
        { text: '증발압력이 높아지고 과열도는 낮아진다.' },
        { text: '응축기가 필요 없어지고 냉동능력이 커진다.' },
      ],
      answer: 1,
      explanation: '팽창밸브를 너무 조이면 증발기로 들어가는 냉매가 줄어듭니다. 그러면 증발압력과 냉동능력은 내려가고, 출구 냉매증기의 과열도는 커집니다. 리퀴드백은 오히려 냉매가 너무 많이 들어가 완전히 증발하지 못할 때 생깁니다. 유사 기출: 2011년 6월 38번, 2016년 3월 25번, 2025년 1회 25번.',
      source: provenance,
      explanationProvenance: provenance,
    },
    {
      number: 13,
      _subject: '냉동냉장설비',
      text: '밀폐된 단단한 용기 속 이상기체를 가열하여 체적이 일정하게 유지될 때 온도와 압력은 어떻게 되는가?',
      choices: [
        { text: '온도가 올라가고 압력도 높아진다.' },
        { text: '온도는 올라가고 압력은 낮아진다.' },
        { text: '온도는 내려가고 압력은 높아진다.' },
        { text: '온도와 압력이 모두 내려간다.' },
      ],
      answer: 1,
      explanation: '체적이 고정된 이상기체는 P/T가 일정합니다. 가열하면 절대온도 T가 올라가므로 압력 P도 같은 방향으로 올라갑니다. 쉽게 외우기: “단단한 통은 커질 수 없어서 압력으로 밀어낸다.” 유사 기출: 2008년 5월 34번, 2015년 5월 21번, 2022년 2회 37번.',
      source: provenance,
      explanationProvenance: provenance,
    },
  ],
};

export const hvacFieldReportRelatedGroups = [
  { topic: '방열기 표시', matches: '2002년 5월 12번 · 2011년 6월 18번 · 2023년 3회 8번' },
  { topic: '송풍기 상사법칙', matches: '2015년 3월 2번 · 2016년 3월 8번 · 2022년 1회 3번 · 2024년 3회 8번' },
  { topic: '냉매·냉동기유', matches: '2012년 3월 34번 · 2014년 3월 28번 · 2019년 8월 26번' },
  { topic: '빙축열·브라인', matches: '2005년 3월 33번 · 2009년 5월 15번' },
  { topic: '캐비테이션', matches: '2012년 3월 46번 · 2015년 3월 60번 · 2019년 8월 46번' },
  { topic: '클린룸·필터', matches: '2019년 3월 17번 · 2022년 1회 8번 · 2026년 2회 13번' },
  { topic: '팽창밸브·이상기체', matches: '2016년 3월 25번 · 2022년 2회 37번 · 2025년 1회 25번' },
];
