import type { PracticalPrompt } from './hvacPracticalTypes';

const sourceNote = 'Q-Net 공조냉동기계산업기사 실기 출제 범위와 공개 반복 유형을 바탕으로 새로 만든 독자 연습문제입니다.';

export const hvacPracticalDrills: PracticalPrompt[] = [
  {
    id: 'hvac-practical-drill-01', group: 'drill', category: 'cycle', difficulty: 'basic', points: 5,
    question: '증기압축 냉동사이클의 냉매 흐름을 증발기부터 순서대로 쓰고, 각 장치에서 냉매가 받는 변화를 짧게 설명하세요.',
    answer: '증발기(열 흡수·증발) → 압축기(압력·온도 상승) → 응축기(열 방출·응축) → 팽창장치(감압) → 증발기',
    explanation: '냉매는 증발기에서 실내 열을 가져오고, 압축기에서 고온·고압이 됩니다. 응축기에서 열을 밖으로 버려 액체가 된 뒤 팽창장치에서 압력이 낮아져 다시 열을 흡수할 준비를 합니다.',
    keyPoints: ['증발기→압축기→응축기→팽창장치 순서', '증발기는 열 흡수', '응축기는 열 방출', '팽창장치는 감압'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-02', group: 'drill', category: 'cycle', difficulty: 'standard', points: 5,
    question: '냉동사이클에서 압축기 입구 냉매가 액체가 아닌 증기여야 하는 이유를 쓰세요.',
    answer: '액체는 거의 압축되지 않아 액압축이 발생하면 밸브·피스톤·스크롤 등에 큰 충격과 파손을 줄 수 있기 때문입니다.',
    explanation: '압축기는 기체 부피를 줄이는 장치입니다. 액체 냉매가 들어오면 순간 압력이 크게 올라 기계 부품이 손상되고 냉동기유도 씻겨 나갈 수 있습니다.',
    keyPoints: ['액체는 거의 압축되지 않음', '액압축 충격', '압축기 파손 위험'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-03', group: 'drill', category: 'cycle', difficulty: 'standard', points: 5,
    question: '냉동능력과 압축기 일이 같을 때 냉동 COP보다 히트펌프 난방 COP가 1만큼 큰 이유를 설명하세요.',
    answer: '응축기 방열량은 증발기에서 흡수한 열과 압축기 일을 합한 값이므로 COP난방=(냉동능력+압축기 일)/압축기 일=COP냉동+1입니다.',
    explanation: '난방에서는 압축기에 넣은 전기에너지도 실내로 버리는 열에 포함됩니다. 그래서 같은 사이클이면 난방 COP가 냉동 COP보다 정확히 1 큽니다.',
    keyPoints: ['응축기 열량=냉동능력+압축기 일', 'COP난방=COP냉동+1'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-04', group: 'drill', category: 'cycle', difficulty: 'advanced', points: 5,
    question: '2단 압축 냉동사이클에서 중간압력을 사용하는 목적을 두 가지 쓰세요.',
    answer: '각 단의 압축비와 토출온도를 낮추고, 체적효율 및 운전효율을 높여 저온 운전을 안정적으로 하기 위해서입니다.',
    explanation: '한 번에 아주 높은 압력까지 압축하면 압축비와 토출온도가 지나치게 커집니다. 압축을 두 번으로 나누고 중간에서 냉각하면 압축기가 덜 힘들게 일합니다.',
    keyPoints: ['단별 압축비 감소', '토출온도 감소', '효율·안정성 향상'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-05', group: 'drill', category: 'cycle', difficulty: 'standard', points: 5,
    question: '과열도와 과냉도의 뜻을 각각 쓰고, 두 값을 확인하는 이유를 설명하세요.',
    answer: '과열도는 흡입증기온도-증발포화온도, 과냉도는 응축포화온도-액관온도입니다. 증발기 냉매 공급 상태와 응축된 액냉매의 안정성을 판단합니다.',
    explanation: '과열도는 증발기에서 냉매가 모두 증발한 뒤 더 데워진 정도이고, 과냉도는 응축된 액체가 더 식은 정도입니다. 둘을 함께 보면 부족충전·과충전·팽창밸브 이상을 구별하는 데 도움이 됩니다.',
    keyPoints: ['과열도=흡입온도-증발포화온도', '과냉도=응축포화온도-액관온도', '냉매 상태 진단'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-06', group: 'drill', category: 'cycle', difficulty: 'standard', points: 5,
    question: '사방밸브가 있는 공기열원 히트펌프에서 냉방과 난방 때 실내 열교환기의 역할을 각각 쓰세요.',
    answer: '냉방 때 실내 열교환기는 증발기, 난방 때는 응축기 역할을 합니다.',
    explanation: '사방밸브가 냉매 흐름을 반대로 바꿉니다. 냉방 때는 실내 열을 흡수하고, 난방 때는 실내로 열을 방출합니다.',
    keyPoints: ['냉방=실내 증발기', '난방=실내 응축기', '사방밸브가 흐름 전환'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-07', group: 'drill', category: 'calculation', difficulty: 'basic', points: 5,
    question: '냉동능력 24 kW, 압축기 입력 6 kW인 냉동기의 COP와 응축기 방열량을 구하세요.',
    answer: 'COP=24÷6=4, 응축기 방열량=24+6=30 kW',
    explanation: 'COP는 얻은 냉동능력을 넣은 일로 나눕니다. 응축기는 증발기에서 가져온 열 24 kW와 압축기가 보탠 6 kW를 모두 버립니다.',
    keyPoints: ['COP=냉동능력÷입력', '응축기 열량=냉동능력+입력', 'COP 4', '30 kW'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-08', group: 'drill', category: 'calculation', difficulty: 'standard', points: 5,
    question: '증발기 입·출구 엔탈피가 각각 250, 400 kJ/kg이고 필요한 냉동능력이 75 kW일 때 냉매 순환량을 구하세요.',
    answer: '냉동효과=400-250=150 kJ/kg, 냉매 순환량=75÷150=0.5 kg/s',
    explanation: '냉매 1 kg이 가져가는 열은 엔탈피 차 150 kJ입니다. 1초에 75 kJ를 가져가려면 75÷150=0.5 kg이 필요합니다.',
    keyPoints: ['냉동효과=출구-입구 엔탈피', '75÷150', '0.5 kg/s'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-09', group: 'drill', category: 'calculation', difficulty: 'standard', points: 5,
    question: '흡입 엔탈피 400 kJ/kg, 토출 엔탈피 450 kJ/kg, 팽창밸브 입구 엔탈피 250 kJ/kg일 때 냉동 COP를 구하세요.',
    answer: '냉동효과=400-250=150 kJ/kg, 압축일=450-400=50 kJ/kg, COP=150÷50=3',
    explanation: '증발기에서 얻은 열을 압축기에 넣은 일로 나눕니다. 엔탈피 단위가 같으므로 그대로 빼고 나누면 됩니다.',
    keyPoints: ['냉동효과 150', '압축일 50', 'COP 3'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-10', group: 'drill', category: 'calculation', difficulty: 'standard', points: 5,
    question: '냉각수 2 kg/s가 응축기에서 5℃ 상승할 때 응축기 방열량을 구하세요. 물의 비열은 4.18 kJ/(kg·K)입니다.',
    answer: 'Q=m×c×ΔT=2×4.18×5=41.8 kW',
    explanation: '1초에 물 2 kg을 5℃ 올리는 열량입니다. kJ/s는 kW와 같으므로 결과는 41.8 kW입니다.',
    keyPoints: ['Q=m c ΔT', '2×4.18×5', '41.8 kW'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-11', group: 'drill', category: 'calculation', difficulty: 'standard', points: 5,
    question: '풍량 2 m³/s의 공기를 10℃ 냉각할 때 현열부하를 구하세요. 공기 밀도 1.2 kg/m³, 비열 1.005 kJ/(kg·K)입니다.',
    answer: 'Q=ρ×풍량×c×ΔT=1.2×2×1.005×10=24.12 kW, 약 24.1 kW',
    explanation: '먼저 1초에 지나가는 공기 질량은 1.2×2=2.4 kg/s입니다. 이 공기 1 kg마다 10℃를 낮추는 열을 계산합니다.',
    keyPoints: ['질량유량=밀도×풍량', 'Q=ρVcΔT', '약 24.1 kW'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-12', group: 'drill', category: 'calculation', difficulty: 'basic', points: 5,
    question: '전체 냉방부하가 30 kW이고 현열부하가 21 kW일 때 현열비(SHF)와 잠열부하를 구하세요.',
    answer: 'SHF=21÷30=0.7, 잠열부하=30-21=9 kW',
    explanation: '전체 열은 현열과 잠열의 합입니다. 현열비는 전체 중 현열이 차지하는 비율입니다.',
    keyPoints: ['SHF=현열÷전열', '0.7', '잠열 9 kW'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-13', group: 'drill', category: 'calculation', difficulty: 'advanced', points: 5,
    question: '증발압력 0.2 MPa, 응축압력 1.8 MPa인 2단 압축장치의 이상적인 중간압력을 구하세요.',
    answer: 'Pm=√(Pe×Pc)=√(0.2×1.8)=√0.36=0.6 MPa',
    explanation: '두 단의 압축비를 같게 나누는 이상적인 중간압력은 두 압력의 기하평균입니다.',
    keyPoints: ['Pm=√(PePc)', '√0.36', '0.6 MPa'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-14', group: 'drill', category: 'calculation', difficulty: 'basic', points: 5,
    question: '진공압이 380 mmHg일 때 절대압력을 kPa로 구하세요. 표준대기압은 760 mmHg=101.325 kPa입니다.',
    answer: '절대압력=(760-380)×101.325÷760=50.6625 kPa, 약 50.7 kPa',
    explanation: '진공압은 대기압에서 빠진 압력입니다. 남은 압력은 760-380=380 mmHg이고, 이는 정확히 대기압의 절반입니다.',
    keyPoints: ['절대압력=대기압-진공압', '380 mmHg', '약 50.7 kPa'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-15', group: 'drill', category: 'operation', difficulty: 'standard', points: 5,
    question: '냉매 부족 때 일반적으로 나타나는 흡입압력, 과열도, 사이트글라스 상태를 쓰세요.',
    answer: '흡입압력은 낮아지고 과열도는 커지며, 액관 사이트글라스에 기포가 계속 보일 수 있습니다.',
    explanation: '냉매가 부족하면 증발기가 굶어 냉매가 일찍 증발합니다. 다만 액관 막힘도 비슷한 증상을 만들 수 있으므로 한 가지 값만 보고 단정하면 안 됩니다.',
    keyPoints: ['흡입압력 저하', '과열도 증가', '사이트글라스 기포 가능', '다른 원인과 함께 진단'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-16', group: 'drill', category: 'operation', difficulty: 'standard', points: 5,
    question: '공냉식 응축기의 응축압력이 비정상적으로 높아지는 원인을 네 가지 쓰세요.',
    answer: '응축기 핀 오염, 송풍기 고장·역회전, 흡입·토출 통풍 방해, 외기온도 상승, 냉매 과충전, 불응축가스 혼입 등이 있습니다.',
    explanation: '응축기에서 열을 제대로 버리지 못하거나 냉매가 지나치게 많으면 고압이 올라갑니다. 압력을 내리기 전에 먼저 공기 흐름과 오염 상태를 확인합니다.',
    keyPoints: ['핀 오염', '송풍 불량', '통풍 방해 또는 외기온도', '과충전 또는 불응축가스'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-17', group: 'drill', category: 'operation', difficulty: 'advanced', points: 5,
    question: '불응축가스가 냉매 회로에 들어갔을 때 나타나는 대표 증상과 조치 방향을 쓰세요.',
    answer: '응축압력과 토출온도가 높아지고 소비동력이 증가합니다. 냉매를 안전하게 회수한 뒤 진공·누설 점검을 하고 규정량을 재충전합니다.',
    explanation: '공기 같은 불응축가스는 응축기에서 액체가 되지 않고 공간을 차지해 압력을 올립니다. 냉매를 대기로 방출하지 말고 회수장비를 사용해야 합니다.',
    keyPoints: ['응축압력 상승', '토출온도·동력 증가', '냉매 회수', '진공 후 재충전'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-18', group: 'drill', category: 'operation', difficulty: 'standard', points: 5,
    question: '증발기 착상이 심해지는 원인과 냉동능력이 감소하는 이유를 설명하세요.',
    answer: '제상 불량, 풍량 부족, 문 개방·수분 유입, 지나치게 낮은 증발온도 등이 원인입니다. 서리가 공기 통로와 열전달을 막아 냉동능력이 감소합니다.',
    explanation: '얇은 서리도 열저항이 되고, 두꺼워지면 공기가 코일을 통과하지 못합니다. 제상장치뿐 아니라 팬과 문 밀폐도 함께 점검합니다.',
    keyPoints: ['제상·풍량·수분 유입 원인', '서리가 열전달 방해', '공기 통로 막힘'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-19', group: 'drill', category: 'operation', difficulty: 'standard', points: 5,
    question: '팽창밸브 감온통의 설치가 불량하면 어떤 문제가 생기는지 쓰고 올바른 설치 원칙을 설명하세요.',
    answer: '실제 흡입관 온도를 잘못 감지해 냉매 공급이 불안정해집니다. 증발기 출구의 깨끗한 수평 흡입관에 단단히 밀착하고 외기 영향을 줄이도록 보온합니다.',
    explanation: '감온통은 과열도를 판단하는 온도 센서입니다. 밀착이 느슨하거나 외기 열을 받으면 밸브가 너무 열리거나 닫혀 헌팅·액압축·냉매 부족 현상이 생길 수 있습니다.',
    keyPoints: ['온도 오감지', '증발기 출구 흡입관에 밀착', '보온', '냉매 공급 불안정'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-20', group: 'drill', category: 'operation', difficulty: 'advanced', points: 5,
    question: '펌프다운 운전의 목적과 일반적인 정지 순서를 설명하세요.',
    answer: '정지 때 증발기와 흡입배관의 냉매를 고압측 수액기에 모아 액냉매 이동을 줄입니다. 온도조절기가 액관 전자밸브를 닫고, 압축기가 계속 운전하다 저압스위치가 작동해 정지합니다.',
    explanation: '압축기를 먼저 꺼 버리는 방식이 아닙니다. 냉매 공급을 먼저 끊고 압축기가 저압측 냉매를 빨아들인 뒤 저압스위치가 압축기를 멈춥니다.',
    keyPoints: ['저압측 냉매를 수액기에 모음', '전자밸브 닫힘', '압축기 운전 지속', '저압스위치 정지'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-21', group: 'drill', category: 'piping', difficulty: 'basic', points: 5,
    question: '동관 브레이징 때 관 안으로 질소를 약하게 흘리는 이유를 쓰세요.',
    answer: '관 내부의 산화를 막아 산화물 스케일이 냉매 회로로 들어가는 것을 줄이기 위해서입니다.',
    explanation: '뜨거운 동관 안에 공기가 있으면 검은 산화물이 생깁니다. 질소는 공기를 밀어내 내부를 깨끗하게 유지합니다.',
    keyPoints: ['관 내부 산화 방지', '산화물 스케일 방지', '질소 퍼지'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-22', group: 'drill', category: 'piping', difficulty: 'standard', points: 5,
    question: '흡입배관 수직 상승부 아래에 오일트랩을 설치하는 이유를 쓰세요.',
    answer: '저부하 때 고인 냉동기유를 모았다가 냉매가스 속도가 올라갈 때 함께 끌어올려 압축기로 회수하기 위해서입니다.',
    explanation: '흡입가스 속도가 느리면 기름이 수직관을 올라가지 못합니다. 트랩에 모인 기름을 한꺼번에 밀어 올려 압축기 윤활유 부족을 예방합니다.',
    keyPoints: ['기름을 모음', '상승관 오일 회수', '압축기 윤활 유지'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-23', group: 'drill', category: 'piping', difficulty: 'standard', points: 5,
    question: '액관에 필터드라이어와 사이트글라스를 설치하는 목적을 각각 쓰세요.',
    answer: '필터드라이어는 수분·산·이물질을 제거하고, 사이트글라스는 액냉매 상태와 수분 지시 상태를 확인합니다.',
    explanation: '필터드라이어는 회로를 청소하는 장치이고 사이트글라스는 상태를 보는 창입니다. 기포가 보인다고 무조건 냉매 부족으로 단정하지는 않습니다.',
    keyPoints: ['필터드라이어=수분·이물 제거', '사이트글라스=액 상태 확인', '기포만으로 단정 금지'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-24', group: 'drill', category: 'piping', difficulty: 'standard', points: 5,
    question: '냉매 배관의 기밀시험과 진공작업의 목적 차이를 설명하세요.',
    answer: '기밀시험은 누설 여부를 확인하고, 진공작업은 회로 안의 공기와 수분을 제거합니다.',
    explanation: '기밀시험이 통과해도 배관 안에는 공기와 수분이 남을 수 있습니다. 그래서 질소 기밀시험 뒤 진공작업을 별도로 합니다.',
    keyPoints: ['기밀시험=누설 확인', '진공=공기·수분 제거', '둘 다 필요'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-25', group: 'drill', category: 'piping', difficulty: 'standard', points: 5,
    question: '냉매 배관 기밀시험에 산소를 사용하면 안 되는 이유와 사용할 수 있는 가스를 쓰세요.',
    answer: '고압 산소는 냉동기유와 반응해 화재·폭발 위험이 있으므로 사용하지 않습니다. 일반적으로 건조 질소를 사용합니다.',
    explanation: '누설을 빨리 찾으려 산소를 넣는 것은 매우 위험합니다. 압력조정기를 단 질소 용기를 사용하고 시험압력은 적용 기준과 장비 허용압력을 확인합니다.',
    keyPoints: ['산소와 기름의 화재·폭발 위험', '건조 질소 사용', '압력조정기 사용'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-26', group: 'drill', category: 'piping', difficulty: 'advanced', points: 5,
    question: '압축기가 응축기보다 높은 곳에 있을 때 토출배관에 오일트랩이 필요한 이유를 설명하세요.',
    answer: '정지 중 응축된 냉매와 냉동기유가 압축기 쪽으로 역류하는 것을 줄이고, 운전 중 오일 회수가 원활하도록 하기 위해서입니다.',
    explanation: '높이 차가 있으면 중력 때문에 액과 기름이 낮은 쪽으로 흐릅니다. 배관의 기울기·트랩·역류 방지 구조로 압축기 액압축과 오일 문제를 줄입니다.',
    keyPoints: ['정지 중 역류 방지', '액냉매의 압축기 유입 방지', '오일 회수'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-27', group: 'drill', category: 'air', difficulty: 'basic', points: 5,
    question: '현열과 잠열을 공기조화의 예를 들어 구분하세요.',
    answer: '현열은 온도를 바꾸는 열이고, 잠열은 수분량을 바꾸는 열입니다. 코일의 공기 냉각은 현열, 수증기 응축에 의한 제습은 잠열입니다.',
    explanation: '온도계 숫자가 변하는 부분은 현열, 공기 속 물의 양이 변하는 부분은 잠열로 생각하면 쉽습니다.',
    keyPoints: ['현열=온도 변화', '잠열=수분 변화', '냉각·제습 예시'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-28', group: 'drill', category: 'air', difficulty: 'standard', points: 5,
    question: '외기 10 kg/s와 환기 30 kg/s를 혼합합니다. 두 공기의 건구온도가 각각 32℃, 24℃일 때 단순 현열 기준 혼합온도를 구하세요.',
    answer: 'tm=(10×32+30×24)÷(10+30)=26℃',
    explanation: '공기량이 많은 환기 24℃ 쪽에 더 가까운 값이 나와야 합니다. 같은 비열로 보면 질량유량 가중평균을 사용합니다.',
    keyPoints: ['질량유량 가중평균', '(320+720)÷40', '26℃'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-29', group: 'drill', category: 'air', difficulty: 'standard', points: 5,
    question: '냉각코일의 입구 공기 엔탈피가 60 kJ/kg, 출구가 40 kJ/kg이고 건공기 질량유량이 2 kg/s일 때 전열부하를 구하세요.',
    answer: 'Q=m×(h입구-h출구)=2×(60-40)=40 kW',
    explanation: '엔탈피 차에는 현열과 잠열이 함께 들어 있습니다. 1 kg당 20 kJ를 빼고 1초에 2 kg이 지나가므로 40 kJ/s입니다.',
    keyPoints: ['Q=mΔh', '엔탈피 차 20', '40 kW'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-30', group: 'drill', category: 'air', difficulty: 'standard', points: 5,
    question: '냉각·제습 과정과 재열 과정을 습공기선도에서 어떻게 이동하는지 설명하세요.',
    answer: '냉각·제습은 온도와 절대습도가 함께 낮아져 왼쪽 아래로 이동하고, 재열은 절대습도가 거의 일정한 채 온도만 올라 오른쪽으로 이동합니다.',
    explanation: '냉각코일 표면에서 수분이 응축되면 공기가 차가워지고 건조해집니다. 재열코일은 물을 더하거나 빼지 않고 온도만 올립니다.',
    keyPoints: ['냉각·제습=왼쪽 아래', '재열=습도비 일정·오른쪽'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-31', group: 'drill', category: 'air', difficulty: 'advanced', points: 5,
    question: '코일 바이패스 팩터가 작다는 뜻과 출구공기 상태에 미치는 영향을 설명하세요.',
    answer: '코일을 충분히 접촉하지 않고 통과하는 공기 비율이 작다는 뜻이며, 출구공기 상태가 코일의 장치노점온도에 더 가까워집니다.',
    explanation: '바이패스 팩터가 0에 가까우면 거의 모든 공기가 코일과 충분히 열교환합니다. 따라서 냉각·제습 효과가 커집니다.',
    keyPoints: ['우회 공기 비율이 작음', '출구가 장치노점에 가까움', '냉각·제습 효과 증가'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-32', group: 'drill', category: 'safety', difficulty: 'basic', points: 5,
    question: '냉매를 대기 중으로 방출하지 않고 회수해야 하는 이유를 두 가지 쓰세요.',
    answer: '온실효과·오존층 영향 등 환경 피해를 줄이고, 작업자의 질식·동상·화재 위험 및 관련 법규 위반을 막기 위해서입니다.',
    explanation: '냉매 종류마다 위험은 다르지만 밀폐공간에서 산소를 밀어내거나 액냉매가 피부에 닿아 동상을 일으킬 수 있습니다. 회수용기와 회수장비를 사용합니다.',
    keyPoints: ['환경 보호', '작업자 안전', '회수장비·회수용기 사용'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-33', group: 'drill', category: 'safety', difficulty: 'standard', points: 5,
    question: '냉동설비 시운전 전 확인사항을 여섯 가지 쓰세요.',
    answer: '기밀·진공 상태, 밸브 개폐, 냉매 충전량, 전원·접지·회전방향, 냉각수·송풍 상태, 오일량, 안전장치 설정 등을 확인합니다.',
    explanation: '누설·수분·닫힌 밸브·역회전·냉각 불량은 시동 직후 큰 고장을 만들 수 있습니다. 압축기를 켜기 전에 눈으로 확인할 항목부터 순서대로 점검합니다.',
    keyPoints: ['기밀·진공', '밸브', '전기·회전방향', '냉각수·송풍', '오일·냉매', '안전장치'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-34', group: 'drill', category: 'safety', difficulty: 'standard', points: 5,
    question: '고압차단스위치와 저압차단스위치의 보호 목적을 각각 설명하세요.',
    answer: '고압스위치는 응축압력의 위험한 상승에서 압축기를 정지시키고, 저압스위치는 지나친 저압·냉매 부족을 보호하거나 펌프다운 정지에 사용합니다.',
    explanation: '두 스위치는 압력이 정상 범위를 벗어났을 때 압축기를 멈춥니다. 원인을 고치지 않은 채 반복 리셋하면 안 됩니다.',
    keyPoints: ['고압 위험 시 정지', '저압·냉매 부족 보호', '펌프다운 사용', '원인 확인 후 복귀'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-35', group: 'drill', category: 'safety', difficulty: 'standard', points: 5,
    question: '냉매 누설을 점검하는 방법을 세 가지 쓰고, 화염식 검지 사용 시 주의할 냉매를 설명하세요.',
    answer: '전자식 누설검지기, 발포액, 질소 가압 후 압력 확인 등을 사용합니다. 냉매 종류와 안전기준에 맞는 검지법을 선택하며, 불꽃을 사용하는 검지는 가연성 냉매에 사용하면 안 됩니다.',
    explanation: '무조건 불꽃을 가까이 대는 방식은 위험합니다. 환기하고 전원을 안전하게 관리한 뒤 냉매 종류에 맞는 전자식 검지기나 발포액을 우선 사용합니다.',
    keyPoints: ['전자식 검지', '발포액', '질소 가압', '가연성 냉매에 불꽃 금지'], sourceNote,
  },
  {
    id: 'hvac-practical-drill-36', group: 'drill', category: 'safety', difficulty: 'advanced', points: 5,
    question: '안전밸브와 파열판의 작동 후 상태 차이를 설명하세요.',
    answer: '안전밸브는 설정압력에서 열렸다가 압력이 내려가면 다시 닫힐 수 있지만, 파열판은 한 번 파열되면 새것으로 교체해야 합니다.',
    explanation: '둘 다 과압을 방출하지만 복귀 방식이 다릅니다. 안전밸브도 작동 뒤에는 누설·설정상태를 점검해야 합니다.',
    keyPoints: ['안전밸브는 재폐쇄 가능', '파열판은 1회 작동', '파열판 교체 필요'], sourceNote,
  },
];
